version: 0.2
 
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      #- IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      # You can choose either the commit ID or the build ID as the information to be added to the IMAGE_TAG for a docker image.
      # - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      #- REPOSITORY_URI= 596560028005.dkr.ecr.ap-south-1.amazonaws.com/docker_blue_green
      - echo Build started on `date`
      - mvn package
      - echo Building the Docker image...
      - docker build -t docker_blue_green .
      - docker tag docker_blue_green:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      #- docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '{"Version":"1.0","ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - printf '[{"name":"java-web-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: 
    # Amazon ECS blue/green deployments require an imageDetail.json file as an input to the deploy action.
    - imageDetail.json
    # Amazon ECS standard deployments require an imagedefinitions.json file as an input to the deploy action.
    # - imagedefinitions.json
cache:
  paths:
    - '/root/.m2/**/*'
