version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install 
      - docker build -t java .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      
